---
- hosts: targets
#  become: yes
  gather_facts: no
  user: centos
  strategy: free

  tasks:
    - name: get file containing installed list
      command: /tmp/jum7 flist installed base {{ inventory_hostname }}

    - name: fetch files from remote
      fetch: src=/tmp/{{ inventory_hostname }}.json dest=/tmp/{{ inventory_hostname }}.json flat=yes
